server {
    listen 80;
    root /app/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://yft.zeabur.app;
        proxy_set_header Host yft.zeabur.app;
        proxy_ssl_server_name on;
    }
}
